### ISSUE TITLE
Not passing through properties

### ISSUE THREAD

**Issue by dceejay** [MaddyTP/node-red-contrib-ezo#1]
Hi

sorry - I wasn't explicit enough in my request to pass through other properties  (like topic (bad example)) - I actually meant all properties - msg.foo msg.bar etc - ie just add yours to the existing incoming message... rather than create a newMsg - just use the incoming msg that triggered the action in the first place, and overwrite the properties you wish (command and payload - and possibly replace topic with the function/mode type).

Thanks

**Comment by MaddyTP** [comment]
Ah! This makes much more sense. Not sure why I didn’t do this in the first place.  I’ll push out a fix later today.
