### ISSUE TITLE
Issues with multiple parameter outputs.

### ISSUE THREAD

**Issue by moonplay85** [MaddyTP/node-red-contrib-ezo#2]
Thank you so much for providing your code.

There is one feature I would like to add.

For EC, humidity sensors, there are more original data values.

Can EC sensor add salinity data and humidity sensor temperature data?

If you issue the "O,T,1" command based on the current humidity sensor and then issue the "R" command again, only the temperature data is displayed.

If you issue the "O,T,0" command again, only humidity data is displayed.

What I want is, can I receive humidity data and temperature data at the same time?

Also, thank you for providing the code.

**Comment by MaddyTP** [comment]
Hi @moonplay85, 

Thanks for supporting my work!  All standard commands from Atlas Scientific are supported and their documentation explains each output parameter must be enabled separately if you want to receive all values when reading.  

![image](https://user-images.githubusercontent.com/45469378/127021586-a5980e5c-e6aa-4cb4-af53-b9f84c01f5ce.png)

**Comment by moonplay85** [comment]
> 안녕하세요 @moonplay85 입니다 .
> 
> 내 작업을 지원해 주셔서 감사합니다! Atlas Scientific의 모든 표준 명령이 지원되며 해당 문서에서는 읽을 때 모든 값을 수신하려면 각 출력 매개변수를 별도로 활성화해야 한다고 설명합니다.
> 
> ![영상](https://user-images.githubusercontent.com/45469378/127021586-a5980e5c-e6aa-4cb4-af53-b9f84c01f5ce.png)
I set the temperature and humidity sensor and turned on the temperature and humidity, but only temperature data came out... So I have a question.

**Comment by MaddyTP** [comment]
@moonplay85 - I had a chance to experiment with multiple outputs today and there is indeed a bug causing inconsistencies.  I have ordered a humidity sensor to confirm the issue, once received I'll work through solving this issue.

**Comment by SonoraTechnical** [comment]
Maddy,
I use multiple outputs using the EC EZO circuit (conductivity, tds, salinity).  I find the results consistent.  

I do however, have issues with the EZO humidity sensor displaying both temp and humidity... but I have the same issue even with the generic i2c libraries and not just your node...  It feels like an i2c bus issue as eventually I just lose the humid/temp readings altogether....

I'm going to start playing around with multiple i2c busses on a Pi4B to see if that helps.

**Comment by MaddyTP** [comment]
> Maddy,
> I use multiple outputs using the EC EZO circuit (conductivity, tds, salinity). I find the results consistent.
> 
> I do however, have issues with the EZO humidity sensor displaying both temp and humidity... but I have the same issue even with the generic i2c libraries and not just your node... It feels like an i2c bus issue as eventually I just lose the humid/temp readings altogether....
> 
> I'm going to start playing around with multiple i2c busses on a Pi4B to see if that helps.

Great to hear!  I was seeing similar with the EC circuit, but wanted to confirm I wasn't missing something.  I'll still dig into this once the humidity sensor comes in to see where the issue lies.

**Comment by moonplay85** [comment]
EC sensors are also problematic.

 Only TDS, salinity, and specific gravity data are displayed.

 Conductivity data is not available. 

Also, thank you for checking.

**Comment by bghull** [comment]
First off, thanks to you both @SonoraTechnical and @MaddyTP for your most excellent work here and in the node-red forums. This library has saved me so much headache with my EZO pH and EC sensors now that I've decided to stop bodging things together with Python exec nodes!

I have an EZO-HUM arriving any day now and I was hoping to use the dual humidity/temperature readouts from it. Any update on this issue, or anything I can do to help troubleshoot once it arrives?

**Comment by MaddyTP** [comment]
@bghull - thank you!  I am still waiting on a humidity sensor to be delivered.  The first one I received was DOA, hopefully the second will be working andI can work through this issue. 

Thank you all for your patience!  I'm not yet sure if this is an issue with the node or an issue with the firmware on these devices.

**Comment by moonplay85** [comment]
It's a really great node.  I ran into a few problems while testing.  Atlas IoT did not apply the saved calibration.  Calibration data seems to disappear when I turn off Atlas IoT, which I have tested.  When I turned on Atlas IoT again, the numerical data came out correctly.  Have you tried the calibration procedure in Nordred?

**Comment by SonoraTechnical** [comment]
You know, I can't get my EZO-HUM working now.... I wonder if it died.  Is it possible we are chasing an issues who's source lies in an unreliable product from it's manufacturer?  I'll keep investingating... I'll see if I can get this thing working again just through a TinyTermnal...

**Comment by MaddyTP** [comment]
Finally received a HUM for testing.  Hopefully I can determine where the issue lies today.  Stand by!

**Comment by MaddyTP** [comment]
Issue resolved in v1.2.1
