### ISSUE TITLE
RGB Sensor Values Not Appearing in Node Red Correctrly

### ISSUE THREAD

**Issue by SimonSparksUK** [MaddyTP/node-red-contrib-ezo#3]
The following is the sample code from Atlas Scientific

https://files.atlas-scientific.com/pi_sample_code.pdf

git clone https://github.com/AtlasScientific/Raspberry-Pi-sample-code.git

pi@hydroponics:/home/RaspberryPiAtlasScientific $ sudo python i2c.py

>> Atlas Scientific I2C sample code
>> Any commands entered are passed to the default target device via I2C except:
  - Help
      brings up this menu
  - List
      lists the available I2C circuits.
      the --> indicates the target device that will receive individual commands
  - xxx:[command]
      sends the command to the device at I2C address xxx
      and sets future communications to that address
      Ex: "102:status" will send the command status to address 102
  - all:[command]
      sends the command to all devices
  - Poll[,x.xx]
      command continuously polls all devices
      the optional argument [,x.xx] lets you set a polling time
      where x.xx is greater than the minimum 1.50 second timeout.
      by default it will poll every 1.50 seconds
>> Pressing ctrl-c will stop the polling

--> DO 97
 - ORP 98
 - pH 99
 - EC 100
 - RTD 101
 - RTD 102
 - FLO 104
 - CO2 105
 - PRS 106
 - FLO 107
 - O2 108
 - PMPL 109
 - RTD 110
 - HUM 111
 - RGB 112
>> Enter command: 112:Cal
Success RGB 112:
>> Enter command: 112:R
Success RGB 112: 255,255,255
>> Enter command: 112:R
Success RGB 112: 75,266,341
>> Enter command: 112:R
Success RGB 112: 45,27,20
>> Enter command:

as you can see it is calibrated to white and then it correctly reads the colours providing 3 integers for the RGB values.

however in Node Red I see the following in a debug node:

![Node Red Message Object](https://user-images.githubusercontent.com/10119404/133655555-711966e6-1f67-4a12-9333-0aac3153f0c3.JPG)

**Comment by SimonSparksUK** [comment]
It is incorrectly distinguishing the array, I think the issue is around line 89 in ezo.js

**Comment by MaddyTP** [comment]
Issue resolved in v1.2.1

**Comment by SimonSparksUK** [comment]
Thanks
