### ISSUE TITLE
1.2.1 Can it be used on nodered?

### ISSUE THREAD

**Issue by moonplay85** [MaddyTP/node-red-contrib-ezo#4]
1.2.1 Can it be used on nodered?

When I checked the palette in Nordred, it was still version 1.2.0.

Can I install NPM?

**Comment by MaddyTP** [comment]
Thanks for the heads up, I had forgotten the Node Red library doesn't update automatically anymore.  It now reflects v1.2.1 in the Node Red library.  Not sure how often the palette manager is refreshed so it might take a day or two to show new revision.

You can install via npm if you don't want to wait.

https://www.npmjs.com/package/node-red-contrib-ezo

**Comment by moonplay85** [comment]
> Thanks for the heads up, I had forgotten the Node Red library doesn't update automatically anymore. It now reflects v1.2.1 in the Node Red library. Not sure how often the palette manager is refreshed so it might take a day or two to show new revision.
> 
> You can install via npm if you don't want to wait.
> 
> https://www.npmjs.com/package/node-red-contrib-ezo

Thank you so much again!!!
