### ISSUE TITLE
update of Node.js v16 for node-red breaks the node-red-contrib-ezo

### ISSUE THREAD

**Issue by SonoraTechnical** [MaddyTP/node-red-contrib-ezo#7]
Maddy, hesitant to post this, because I sense it's an issue with an underlying comms library...

I know that you are using fivdi/i2c-bus for i2c bus serial communications... he states that his work is compatible with node.js v16... 

It's not just your stuff, i found the Nodes for NCD hardware that utilize i2c are broken as well... So i guess this issue is more of a notification to you, rather than an alert for you to fix something.

**Comment by MaddyTP** [comment]
> Maddy, hesitant to post this, because I sense it's an issue with an underlying comms library...
> 
> I know that you are using fivdi/i2c-bus for i2c bus serial communications... he states that his work is compatible with node.js v16...
> 
> It's not just your stuff, i found the Nodes for NCD hardware that utilize i2c are broken as well... So i guess this issue is more of a notification to you, rather than an alert for you to fix something.

Thanks! I’m not running Node v16 but I’ll spin up an instance to test this weekend.

**Comment by SimonSparksUK** [comment]
I am using Node v14.18.1 on a Raspberry Pi 4B+ 8GB model.

![image](https://user-images.githubusercontent.com/10119404/141507831-a8f569cf-1873-4d44-be96-0d4f8c1bdedf.png)

This is a screenshot of my I2C devices all of which are HATs which are stacked up on the Raspberry Pi e.g. Whitebox Labs EZO HAT.

The device which is identified as 1e is an Atlas Scientific Large Peristaltic Pump.

This is what I see on the console when I try to send the command D,* to the device using your library.

12 Nov 17:15:02 - [error] [ezo:Peristaltic Dosing Pump - 21 - Additive - Water] Error: EREMOTEIO: remote I/O error, read
12 Nov 17:15:03 - [error] [ezo:Peristaltic Dosing Pump - 21 - Additive - Water] Error: EREMOTEIO: remote I/O error, read

This is what I see in the debug window of Node RED

![image](https://user-images.githubusercontent.com/10119404/141508435-7cd0feb7-8d06-4b66-b107-de0583aeefcc.png)

Any help would be much appreciated.

I am not blaming your library as I have had it working before, I think there might be a mix of software libraries that is causing the issue.

**Comment by MaddyTP** [comment]
> I am using Node v14.18.1 on a Raspberry Pi 4B+ 8GB model.
> 
> ![image](https://user-images.githubusercontent.com/10119404/141507831-a8f569cf-1873-4d44-be96-0d4f8c1bdedf.png)
> 
> This is a screenshot of my I2C devices all of which are HATs which are stacked up on the Raspberry Pi e.g. Whitebox Labs EZO HAT.
> 
> The device which is identified as 1e is an Atlas Scientific Large Peristaltic Pump.
> 
> This is what I see on the console when I try to send the command D,* to the device using your library.
> 
> 12 Nov 17:15:02 - [error] [ezo:Peristaltic Dosing Pump - 21 - Additive - Water] Error: EREMOTEIO: remote I/O error, read 12 Nov 17:15:03 - [error] [ezo:Peristaltic Dosing Pump - 21 - Additive - Water] Error: EREMOTEIO: remote I/O error, read
> 
> This is what I see in the debug window of Node RED
> 
> ![image](https://user-images.githubusercontent.com/10119404/141508435-7cd0feb7-8d06-4b66-b107-de0583aeefcc.png)
> 
> Any help would be much appreciated.
> 
> I am not blaming your library as I have had it working before, I think there might be a mix of software libraries that is causing the issue.
> 
> I am reading several other Atlas Scientific Probes
> 
> ![image](https://user-images.githubusercontent.com/10119404/141509263-892a20cc-6fd1-4ec5-a0f5-dcb1763af5c5.png)
> 
> But for some reason the Humidy Sensor is not returning sensible data...
> 
> ![image](https://user-images.githubusercontent.com/10119404/141509505-c7e40580-31cd-4f06-b64c-f774f17cb5ee.png)
> 
> If I use the Whitebox Labs sample code or the Raspberry Pi sample code from the Atlas Scientific GitHub then I can Successfully POLL all of the devices.
> 
> ![image](https://user-images.githubusercontent.com/10119404/141510702-eca038f0-dee9-453b-aa5d-6fc4afdaa096.png)
> 
> The data sheet says that I can do 1 reading per 300 milliseconds in I2C mode.
> 
> ![image](https://user-images.githubusercontent.com/10119404/141513137-033608be-a489-4cc1-8ddc-718b98276b9c.png)
> 
> I do a sensor read every 5 seconds using a Node Red Inject with a 5 Second Interval and I add 100ms delays in between each sensor just for good measure.
> 
> ![image](https://user-images.githubusercontent.com/10119404/141513429-e34094cc-ad74-478a-9738-b01f17248465.png)

The 'remote I/O error' you are receiving is related to the I2C library and your device configuration.  This might offer some guidance:  https://github.com/fivdi/i2c-bus/issues/36

I've confirmed both PMP and HUM are working as expected on a fresh install of Debian Buster on Raspi 4, with double stacked Whitebox hats.

Also, in the future please create a new issue to keep other issues clean.

**Comment by SimonSparksUK** [comment]
I've added the following lines to the Raspberry Pi Boot Config file

dtparam=i2c_arm=on
dtparam=i2c_baudrate=10000
dtparam=i2c_arm_baudrate=10000

and rebooted and I no longer get the IO Errors in Node Red however when I send the command I see the LED change from Blue to Green and then back to Blue

BUT the PMP does not rotate, I confirmed that the pump has 24v at its terminals and the polarity is correct.

Not sure what to try next.... do you have any suggestions?

**Comment by SimonSparksUK** [comment]
FYI this is not a little project at all....

There are 20 Atlas Scientific Peristaltic Pumps

![2021-09-22 16 14 09](https://user-images.githubusercontent.com/10119404/141523675-c85d8609-fe73-439e-9523-75e4efa5aa8f.jpg)

This is the Raspberry Pi with all the HATs stacked up

![2021-11-12 19 25 35](https://user-images.githubusercontent.com/10119404/141523865-e6693f73-622c-4497-bb5a-b03a3124bf56.jpg)

This is the solution so far...

![2021-11-12 19 29 16](https://user-images.githubusercontent.com/10119404/141524074-8c8c921f-281a-4915-a478-9abeabc10bc0.jpg)

**Comment by SimonSparksUK** [comment]
I spoke too soon the error are not all gone with the speed reduction and now I have some different ones.

![image](https://user-images.githubusercontent.com/10119404/141524581-c13523ca-f9fa-4250-9736-25c348724299.png)

**Comment by MaddyTP** [comment]
> I spoke too soon the error are not all gone with the speed reduction and now I have some different ones.
> 
> ![image](https://user-images.githubusercontent.com/10119404/141524581-c13523ca-f9fa-4250-9736-25c348724299.png)

Change your `msg.command` to `msg.payload`.

**Comment by MaddyTP** [comment]
> Maddy, hesitant to post this, because I sense it's an issue with an underlying comms library...
> 
> I know that you are using fivdi/i2c-bus for i2c bus serial communications... he states that his work is compatible with node.js v16...
> 
> It's not just your stuff, i found the Nodes for NCD hardware that utilize i2c are broken as well... So i guess this issue is more of a notification to you, rather than an alert for you to fix something.

Just did a fresh install to confirm and all is working as expected:

Debian Bullseye 64bit Lite
NodeJS v16.13.0
NPM v8.1.0
Node-Red v2.1.3
Ezo v1.3.0
