### ISSUE TITLE
Calibrate Command possible

### ISSUE THREAD

**Issue by pascone10** [MaddyTP/node-red-contrib-ezo#9]
Hi Maddy, Thank you for this node! I am trying to figure out how to combine a message to calibrate a PH sensor. Is that possible? The Atlas scientific documentation says we need 3 arguments and I am not sure how to do that in node-red. Thanks again!

**Comment by MaddyTP** [comment]
Hi @pascone10, according to the Atlas docs you should send each calibration command one after the other starting with the Cal,Mid,N.  

Calibrate mid with pH 7.0 standard:

`
msg.command = 'Cal,Mid'
`
`
msg.payload = 7.0
`

or

`
msg.payload = 'Cal,Mid,7.0'
`

And if multi-point calibration is desired one would send additional messages at the low (4.0) and high (10.0) points.
